name: publish to Reposilite

on:
  release:
    types: [ published ]

jobs:
  publish_lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set version
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/} | sed "s/^v//")" >> $GITHUB_ENV
          echo "refs: ${{ github.ref }}"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Gradle Build and publish to Reposilite
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: |
            clean
            build
            publish
            -Pversion=${{ env.RELEASE_VERSION }}
        env:
          REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
          REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}